### ISSUE TITLE
Missing construct dependency in README

### ISSUE THREAD

**Issue by Aztorius** [RealityNet/teleparser#1]
**Describe the bug**
Crash because of missing dependency.
Fixed with `pip install --user construct`

**Script logs**
```
Traceback (most recent call last):
  File "./teleparser.py", line 45, in <module>
    import tblob
  File "/home/william/outils/teleparser/tblob.py", line 33, in <module>
    from construct import * # pylint: disable=W0401,W0622,W0614
```

**OS used to execute the script (please complete the following information):**
 - OS: Linux

**Telegram app (please complete the following information):**
*

**Additional context**

**Comment by dfirfpi** [comment]
Thanks @Aztorius , I'll add the requirements file.
