### ISSUE TITLE
Linux crash bescause of DOS endline char

### ISSUE THREAD

**Issue by Aztorius** [RealityNet/teleparser#2]
**Describe the bug**
Cannot execute teleparser.py with bash.
Because of the endline char on the first line of teleparser.py, bash cannot execute python3.
Using `python3 teleparser.py` it works.

**Script logs**
```
$ ./teleparser.py
bash: ./teleparser.py : /usr/bin/python3^M : mauvais interpréteur: Aucun fichier ou dossier de ce type
```

**OS used to execute the script (please complete the following information):**
 - OS: Linux

**Telegram app (please complete the following information):**
*

**Additional context**

**Comment by dfirfpi** [comment]
Thanks, I'll switch to *tux newlines.
