### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by ufgf** [RealityNet/teleparser#6]
**Describe the bug**
I'm trying to use teleparser on cache4.db and it doesn't seem to work, I run following command: `python3 teleparser.py cache4.db out_folder` and it gives me this error:
`sqlite3.DatabaseError: database disk image is malformed`

**Script logs**
https://pastebin.com/iL0EPVvN

**OS used to execute the script (please complete the following information):**
 - OS: Ubuntu LTS 20.04

**Telegram app (please complete the following information):**
- Telegram App Version: 6.3.0
- Smartphone OS: Android 10, crDroid
- Smartphone brand: Xiaomi

**Additional context**
`cache4.db-wal` and `cache4.db-shm` I also put next to the `cache4.db`

**Comment by dfirfpi** [comment]
hi @ufgf 
the script has no role here. Most likely the db is partially corrupted.

Please check the steps in the following resources
https://sqliteviewer.com/blog/database-disk-image-malformed/
https://techblog.dorogin.com/sqliteexception-database-disk-image-is-malformed-77e59d547c50?gi=b5d343e2e000
